let mydata; 
console.log(typeof(mydata)); 
mydata=null; 
consl=ole.log(typeof(mydata)); 
mydata=""; 
console.log(typeof(mydata)); 
mydata=10; 
console.log(typeof(mydata)); 
mydata=10.50; 
console.log(typeof(mydata)); 
mydata=98797889788968997n; 
console.log(typeof(mydata)); 
mydata=true; 
console.log(typeof(mydata)); 
mydata=[1,2,3,4]; 
console.log(typeof(mydata));